MemoRodz/CapaciTechKids

src/App.jsx
=> add comentario hola mundo

.gitignore, package-lock.json, src/pages/Courses/Courses.jsx
actualización component Course con conexión a base de datos a través de pedido fetch
=> changes/CourseComponent :

src/App.jsx, src/component/Layout/Nav/Nav.jsx, src/component/index.js, src/pages/Create/Create.jsx, src/pages/Create/Create.module.css, src/pages/home/Home.jsx, src/pages/index.js
Se agrego el componente Create
=> add component Create

src/component/Course/Course.jsx
=> div en course

src/component/Course/Course.jsx, src/component/Filters/CategoryFilter.jsx, src/component/Filters/ScoreFilter.jsx, src/component/index.js, src/main.jsx, src/pages/Courses/Courses.jsx, src/pages/Create/Create.jsx, src/pages/home/Home.jsx, src/redux/slices/courses.silce.js, src/redux/slices/index.js, src/redux/slices/instructors.slice.js, src/redux/store.js
Reducer and filters created
En el componente de cursos (Courses.jsx) descomentar la linea 11 y pasarle a la funcion getAllcourses la url del back
=> add reducer and filters

src/pages/Create/Create.jsx
=> FIX Create

src/component/Course/Course.jsx, src/pages/Courses/Courses.jsx, src/redux/slices/courses.silce.js
Agregue el filtro por score, faltaria agregar los cambios para el filtro por categoria
=> Filtro por score

src/component/Filters/CategoryFilter.jsx, src/redux/slices/categoriesSlice.js, src/redux/slices/coursesSlice.js
Agregue filtro por categoria y score
=> add filters by score and category

src/component/Filters/CategoryFilter.jsx, src/redux/slices/coursesSlice.js
1.Cambie el filtro de categorias, antes un dropdown select, ahora checkboxes.
2.Cree un estado local (array de seleciones) para controlar las checkboxes.
3.Ahora cuando una checkbox cambie, se despacha una action al reducer con el estado local.
=> Category filter changed to checkboxes

src/component/Course/Course.jsx, src/component/Estrella/Estrella.jsx
por fin se arreglo las estrellas
=> fix Estrellas

src/component/Filters/CategoryFilter.jsx, src/component/Filters/CategoryFilter/CategoryFilter.jsx, src/component/Filters/CategoryFilter/CategoryFilter.module.css, src/component/Filters/ScoreFilter/ScoreFilter.jsx, src/component/index.js, src/pages/Courses/Courses.jsx, src/pages/Courses/Courses.module.css, src/pages/home/Home.jsx, src/redux/slices/categoriesSlice.js
1. Agregue botones a los filtros
2. Añadí estilo un basico a los filtros
=> Filtros y estilos

src/component/Filters/CategoryFilter/CategoryFilter.jsx, src/component/Filters/CategoryFilter/CategoryFilter.module.css, src/component/Filters/ScoreFilter/ScoreFilter.jsx, src/pages/Courses/Courses.module.css
1. Ahora los botones de filtro por categoria se desactivan al selecionar una categoria.
2. El input de number es de tipo range.
=> Category filter buttons disable on select

src/component/Course/Course.jsx, src/component/Estrella/Estrella.jsx, src/pages/Detail/Detail.jsx, src/pages/Detail/Detail.module.css
se agrego al detail datos de la tabla review y tabla course
Ademas se integro axios para extraer de BD dicha info
=> add datos a Detail

src/pages/Courses/Courses.jsx, src/pages/Create/Create.jsx, src/redux/slices/coursesSlice.js
bug de filtros fixeado.
bug de create fixeado.
=> fixed/ bug filters :

index.html, src/component/Layout/Footer/Footer.jsx, src/component/Layout/Footer/Footer.module.css, src/component/Layout/Nav/Nav.jsx, src/component/Layout/Nav/Nav.module.css, src/global.css, src/pages/home/Home.jsx, src/pages/home/Home.module.css
1. Monserrat font
2. Home and Nav styles
=> monserrat font, home and nav styles

src/component/Course/Course.jsx, src/component/Course/Course.module.css, src/component/Filters/CategoryFilter/CategoryFilter.jsx, src/component/Filters/CategoryFilter/CategoryFilter.module.css, src/component/Filters/ResetFilters/ResetFilters.module.css, src/component/Filters/SortByScore/SortByScore.jsx, src/component/Filters/SortByScore/SortByScore.module.css, src/pages/Courses/Courses.jsx, src/pages/Courses/Courses.module.css
=> Courses styles

src/component/Course/Course.jsx, src/component/Filters/CategoryFilter/CategoryFilter.jsx, src/component/Layout/Nav/Nav.jsx, src/pages/Detail/Detail.jsx
=> Actualizaciones Front 

src/pages/Create/Create.jsx
validación en create
- requerido
- mínimo
- máximo
- placeholder
=> validate form create

src/App.jsx, src/guards/authGuard.jsx, src/guards/index.js, src/pages/Dashboard/Dashboard.jsx, src/pages/Student/Student.jsx, src/pages/Teacher/Teacher.jsx, src/pages/index.js, src/redux/reducers.js, src/redux/slices/coursesSlice.js, src/redux/slices/index.js, src/redux/slices/userSlice.js
1. User state agregado al store
2. AuthGuard component para las rutas de usuarios. Lo que hace este 
componente es rebotar al usuario que no este autenticado, en este caso
lo manda al home.
3. Panel de student y teacher (Estan sin contenido solo un div).
4. Rutas para student y teacher "dashboard/student" y "dashboard/teacher"
En el proximo PR incuire las rutas en español
=> Panel de student y teacher. rutas protegidas

src/pages/Dashboard/Dashboard.jsx
Agregue el import que faltaba en el dashboard
=> Routes import que faltaba en el dashboard.

src/context/TeacherCoursesContext.jsx, src/pages/Courses/Courses.jsx, src/pages/Teacher/ActiveCourse/ActiveCourse.jsx, src/pages/Teacher/ActiveCourses/ActiveCourses.jsx, src/pages/Teacher/ActiveCourses/ActiveCourses.module.css, src/pages/Teacher/DeleteCourse/DeleteCourse.jsx, src/pages/Teacher/DeletedCourses/DeletedCourses.jsx, src/pages/Teacher/DeletedCourses/DeletedCourses.module.css, src/pages/Teacher/Teacher.jsx, src/pages/Teacher/Teacher.module.css, src/pages/home/Home.jsx
1. TeacherCourses context creado.
2. ActiveCourses y DeletedCourses ahora comparten un estado que viene de context.
3. Estilos basicos al panel de profesor
=> Teacher dashboard

src/App.jsx, src/component/Layout/Nav/Nav.jsx, src/component/Login/Login.jsx, src/component/Logout/Logout.jsx, src/hooks/useLocalStorage.js, src/pages/Dashboard/Dashboard.jsx, src/pages/home/Home.jsx, src/redux/slices/userSlice.js
1. Agregue un custom hook para Almacenar el objeto user de useAuth0 en localstorage.
2. En el primer render se postea y luego se trae el user de la base de datos.
3. Y se despacha una action para guardar el user en la store de redux.
=> User login save in localstorage user create in db

src/component/Layout/Nav/Nav.jsx, src/pages/Dashboard/Dashboard.jsx, src/pages/Student/Student.jsx, src/pages/Teacher/Create/Create.jsx, src/pages/Teacher/Create/Create.module.css, src/pages/Teacher/Teacher.jsx, src/pages/Teacher/TeacherCourses/TeacherCourses.jsx, src/pages/Teacher/TeacherCourses/TeacherCourses.module.css, src/pages/Teacher/index.js, src/redux/slices/userSlice.js
1. Arregle el condicional del nav, antes trigereaba un render loop infinito.
2. El nav tiene un link para ir al dashboard de student o instructor, dependiendo de su userRole.
3. Ahora el dashboard de instructor tiene una ruta para los cursos y otra para el create con sus respectivos links.
Nota: si quieren darle mas estilos o contenido al dashboard de student o teacher sin tener que loguearse, harcodeen 
el state de user en el redux (userSlice).
=> Instructor dashboard routes y fix del fetch en nav

src/component/Layout/Nav/Nav.jsx, src/context/TeacherCoursesContext.jsx, src/models/baseUrl.js, src/pages/Courses/Courses.jsx, src/pages/Detail/Detail.jsx, src/pages/Teacher/ActiveCourse/ActiveCourse.jsx, src/pages/Teacher/Create/Create.jsx, src/pages/Teacher/DeleteCourse/DeleteCourse.jsx
Cree una constante que contiene la ruta base del back en desarollo "http:/localhost:3001" y la importe en todos los axios donde se usa, de esta forma cuando hagamos el proximo deploy, solo habra que cambiar esa constante.
=> baseUrl constant

package-lock.json, package.json, src/pages/Admin/Admin.jsx, src/pages/Admin/Users/Admins/Admins.jsx, src/pages/Admin/Users/BannedUsers/BannedUsers.jsx, src/pages/Admin/Users/Instructors/Instructors.jsx, src/pages/Admin/Users/Students/Students.jsx, src/pages/Admin/Users/Users.jsx
=> migración material ui v4 a v5

package-lock.json, package.json, src/App.jsx, src/pages/Video/Player/Player.jsx, src/pages/Video/Player/Player.module.css, src/pages/Video/Sidebar/Sidebar.jsx, src/pages/Video/Sidebar/Sidebar.module.css, src/pages/index.js
COMPONENTE REPRODUCTOR DE VIDEO
=> add Video y Sidebar

src/component/Course/Course.jsx, src/pages/Admin/Users/Admins/Admins.jsx, src/pages/Admin/Users/BannedUsers/BannedUsers.jsx, src/pages/Admin/Users/Instructors/Instructors.jsx, src/pages/Admin/Users/Students/Students.jsx
al fin me salió lpm como 1h estuve con esto
=> userlist c/ switch para act/desac. con rerender :D

src/pages/Admin/ActiveCourse/ActiveCourse.jsx, src/pages/Admin/DeleteCourse/DeleteCourse.jsx, src/pages/Teacher/ActiveCourse/ActiveCourse.jsx, src/pages/Teacher/Create/Create.jsx, src/pages/Teacher/Create/Create.module.css, src/pages/Teacher/DeleteCourse/DeleteCourse.jsx
ssssiiiiiiiiiiiiiiiiii :D
era lo siguiente:
el nombre de los campos estaba en español mientras que el estado los recordaba con nombre en inglés. 
;)
=> create form funciona. duracion ahora en minutos ;)

package-lock.json, package.json, src/component/Course/Course.jsx, src/component/Layout/Nav/Nav.jsx, src/hooks/useCourses.js, src/pages/Courses/Courses.jsx, src/services/fetchCourses.js
**Importante**: hacer npm install, para el swr 
1. Agregue el swr para hacer el get de los cursos 
2. Cree un custom hook "useCourses" para traer los cursos con el swr 
3. Ahora el useEffect de courses revisa si hay cambios en la data que le manda el back para hacer un nuevo render
Nota: Si x algo nececitan revertirlo, simplemente comenten la linea 14 de courses donde esta "useCourses" y al useEffect cambienle el dispatch a como esta en el comentario de la linea 17.
=> Implementacion de Swr 

src/component/Layout/Nav/Nav.jsx, src/component/Login/Login.jsx, src/component/Profile/Profile.jsx, src/pages/Admin/AdminProfile/AdminProfile.module.css, src/pages/Student/Student.jsx, src/pages/Student/Student.module.css, src/pages/Student/StudentProfile/StudentProfile.module.css, src/pages/Teacher/Teacher.module.css, src/pages/Teacher/TeacherProfile/TeacherProfile.module.css
1. Agregue un condicional al profile de nav para que renderice correctamente la imagen de perfil
2. Estilos al profile de users (Admin, Student, Instructor)
=> Estilos al profile de los users y condicional en el componente Profile del nav

package-lock.json, package.json, src/component/Layout/Nav/Nav.jsx, src/global.css, src/pages/Admin/index.js, src/pages/Video/Player/Player.jsx, src/pages/Video/Review's form/review.jsx
1. Agregue el sweet alert, ahora sale un alert bien cheto al enviar una review
2. Fix al player ahora al momento de enviar la review no sale el video
3. Agregue un boton para retroceder, que permite ver los videos anteriores
4. Le di un min height de 90vh al main en el global.css para q el footer qdara abajo
=> Sweet alert y un fix al player

package-lock.json, package.json, src/component/Upload/Upload.jsx, src/pages/Teacher/Create/Create.jsx, src/pages/Teacher/Create/Create.module.css
1. Se ha validado todos campos del form
2. Se ha agregado una alerta de "Curso ha sido Creado"
3. en Upload, se requerido subir una imagen al momento de crear el curso. Sin embargo se demora en cargar (OTRO BUG PARA ARREGLAR)
=> validate Create Form

src/component/Layout/Nav/Nav.jsx, src/component/Profile/Profile.jsx, src/pages/Student/StudentProfile/StudentProfile.jsx
Solo cambiamos lógica de los estados y un pequeñito cambio en funcionalidad de nav uwu
=> fixed user state

src/pages/Detail/Detail.jsx, src/pages/Detail/DetailCard/DetailCard.jsx
1. Ahora el link de cards renderiza el correspondiente detail cuando lo clickean
2. Agregue el pathname del useLocation hook al arreglo de dependencias del useEffect en Detail.jsx
3. Removi varios console.log que estaban en DetailCard.jsx y Detail.jsx
=> Fix al link de las cards en detail

src/pages/Detail/Detail.jsx
1. Se tiene los iconos para compartir por Facebook y Whatsapp el curso.
=> Link de Compartir Cursos

src/component/Course/Course.jsx, src/component/Upload/Upload.jsx, src/pages/Student/StudentProfile/StudentProfile.jsx, src/pages/Teacher/Create/Create.jsx, src/pages/Teacher/TeacherProfile/TeacherProfile.jsx, src/redux/slices/userSlice.js
Se debuggeo la creación de cursos. Ya el curso creado se guarda con imagen y se renderiza con ella en courses
ya el cursos creado no rompe el componente courses
Adiciones: Profesores ya tiene sus cambios en profile trabajando bien
=> Debuggeos generales y adiciones 

src/component/Course/Course.jsx, src/pages/Detail/Detail.jsx
1. Se agrego la nueva ruta con el promedio del score segun las reviews
2. Se quito las importaciones no utilizadas en Courses (iconos)
=> fix Detail y Course (sacar imports no utilizadas)

src/pages/Detail/Detail.jsx, src/pages/Teacher/Create/Create.jsx, src/pages/Video/Player/Player.jsx
Create cursos ya agrega videos, falta correción pequeña de estilos (perdonenme por favor no se estilar jeje
Puede agregar varios videos
Se volvió a incluir el axios que guarda en base de datos la relacion de cursos por estudiante( no la borren pls :'(
[added : agregada ruta que guarda las lectures que mira cada usuario.
=> Added: create y ruta lectures

src/pages/Teacher/ActiveCourse/ActiveCourse.jsx, src/pages/Teacher/ActiveCourse/ActiveCourse.module.css, src/pages/Teacher/Create/Create.jsx
Nota: hay que hacerle mas estilos a las cards del create de teacher (DeleteCourse.jsx y ActiveCourse.jsx)
=> Form de create corregi el width en 3 campos y arregle la card de course en el create de teacher

src/component/Login/Login.jsx, src/models/baseUrl.js, src/pages/Detail/Detail.jsx
1. Ahora cuando el entren al detail de un curso siendo "Instructor" el boton empezar no renderizara.
=> Cambios al boton "Empezar"

src/pages/About/About.jsx, src/pages/About/About.module.css
Estilos para que en el ABOUT este tanto el form de contactanos y la info de nosotros
=> Detalles en el about

src/hooks/useCourses.js, src/models/baseUrl.js, src/pages/Courses/Courses.jsx, src/utils/coursesAdapter.js
1.Cree un adapter para los cursos
2.Ahora en el array de cursos cada objeto (curso), tiene una propiedad Score que se agrega mediante el adapter (coursesAdapter.js)
3.Ahora el boton de sort x max y min deberia funcionar correctamente, ya q la propiedad Score esta como antes.
=> Adapter para cursos 

src/App.jsx, src/models/baseUrl.js, src/pages/AIProfessor/AIProfessor.jsx, src/pages/AllReviews/AllReviews.jsx, src/pages/AllReviews/AllReviews.module.css, src/pages/Detail/Detail.jsx, src/pages/Detail/DetailCard/DetailCard.jsx, src/pages/index.js
debugueados nombres e imagenes de los reviews
Detail Card andando
Muestra todos los reviews si clickeas en el botton de reviews dentro de detail!!! 
Debugueitos varios
=> Debugueos y all reviews
